### ISSUE TITLE
Home / logotipo / video

### ISSUE THREAD

**Issue by mamanidario19** [noelialiquin/pilis-mod2-Liquin-Mamani#1]
**Hola @noelialiquin ! como elegimos que nuestro proyecto sea sobre la exposición vinícola hice esta imagen para la sección "home" con el efecto de letras detrás de algunos objetos:** 

![expo vinicola](https://user-images.githubusercontent.com/32744941/186740322-399c02a3-b7ab-489c-90b4-e946501e2884.png)

**Vi tambien que estas haciendo el navbar, así que podría ayudarte con la imagen del logo, pensando en algo como esto :**
![logo1](https://user-images.githubusercontent.com/32744941/186739946-bace753a-71e5-4e49-b9a9-accceae0eabe.png)
**podriamos cambiar la palabra "vinos" por algo distinto no?** 

**Contarte también que estoy editando un video para cumplir con esa sección y la del clima.**

**Que te parece? espero tu respuesta jeje**

![img](https://media.giphy.com/media/QM5lHSyFjz1XW/giphy.gif)

**Comment by noelialiquin** [comment]
Hola así quedaría el navbar el logo no lo puse por falta unos cambios nos? 
no pude captura el hover seria una línea  border-bottom
![Captura1](https://user-images.githubusercontent.com/107735467/186750177-b2792868-79ee-46d0-a068-fb130bc4343e.JPG)

**Comment by mamanidario19** [comment]
Asi es, ahora voy a terminar el logo y hacer un fork para las siguientes secciones, la linea me gusta! jeje
