### ISSUE TITLE
Add sections

### ISSUE THREAD

**Issue by mamanidario19** [noelialiquin/pilis-mod2-Liquin-Mamani#2]
Saludos! paso a dejar un issue para proponer los siguientes cambios : 
Home: 
![image](https://user-images.githubusercontent.com/32744941/186973197-a844ebf3-f8d6-4865-bb16-d01915dc3cc8.png)
Evento: 
![image](https://user-images.githubusercontent.com/32744941/186973266-e9c3ae57-0cc9-4c74-863a-7817ceb45747.png)
Nosotros: 
![image](https://user-images.githubusercontent.com/32744941/186973325-3debbe4c-e300-4e34-8804-d7ad81d158fc.png)
Logo final (PNG ):
![image](https://user-images.githubusercontent.com/32744941/186973397-40da6556-f55e-4fb8-acad-b07a41dfbfd5.png)

**Comment by noelialiquin** [comment]
Hola muy Bueno imagenes sobre nosotros no serian de personas?

**Comment by mamanidario19** [comment]
Uhh si me equivoque, ahora busco una imagen nueva y termino de editar los iconos y te aviso
